repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: debug-statements
  - repo: https://github.com/psf/black
    rev: 24.4.1
    hooks:
      - id: black
        language_version: python3.9
      - id: black-jupyter
        language_version: python3.9
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
